name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'  # GitHub Pages와 호환되는 Ruby 버전
          bundler-cache: false

      - name: Configure Bundler
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle config set --local deployment 'true'
          bundle config set --local frozen 'false'
      
      - name: Install dependencies
        run: |
          rm -f Gemfile.lock
          bundle install
      
      - name: Build site
        run: JEKYLL_ENV=production bundle exec jekyll build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site